apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sample-eks-cluster
  region: ap-northeast-1
  version: "1.22"

nodeGroups:
  - name: sample-eks-ng
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        awsLoadBalancerController: true
        autoScaler: true
        cloudWatch: true
